name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: ./test-create.exe
        if: always()
      # - run: ./test/bin/tvfs_test_x64.exe
      #   if: always()
